#!/usr/bin/env bash
# tools/slc-install.sh — install slc-cli + the GNU ARM toolchain via Silicon
# Labs' slt tool, and fetch the exact Gecko SDK revision this project is
# pinned to. Mirrors the caching approach in the Tuya_IH-K663 project's
# tools.mk: everything lands under a gitignored cache dir, re-runs are free
# once cached, and CI/local Docker builds use the identical script.
#
# IMPORTANT — SDK sourcing: `slt install simplicity-sdk` pulls Silicon Labs'
# newer Conan-based "Simplicity SDK" line (2025.12+), which is a DIFFERENT,
# incompatible product from the Gecko SDK 4.4.6 both .slcp files in this repo
# are pinned to (`sdk: {id: gecko_sdk, version: 4.4.6}`). slc-cli's -s/--sdk
# flag accepts any local directory containing an .slcs file, so instead of
# going through slt for the SDK, this script clones the SiliconLabs/gecko_sdk
# GitHub repo at tag v4.4.6 directly — pinning the exact revision Studio has
# been building against, not whatever slt considers "latest".
#
# Usage:
#   tools/slc-install.sh              # install (skips steps already cached)
#   tools/slc-install.sh clean        # wipe the cache and start over
#
# On success, writes tools/.cache/env.sh with SLC_CLI_DIR, TOOLCHAIN_DIR,
# SDK_DIR and a ready-to-source PATH. Callers (tools/slc-build.sh, CI steps)
# do:  source tools/.cache/env.sh
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root

CACHE_DIR="tools/.cache"
BIN_DIR="$CACHE_DIR/bin"
ENV_FILE="$CACHE_DIR/env.sh"

# slt itself: check for a newer patch release if this 404s — Silicon Labs
# doesn't publish an index, bumping the patch number and re-running is the
# documented way to find the current one.
SLT_VERSION="${SLT_VERSION:-1.2.2}"
SLT_URL="https://www.silabs.com/documents/public/software/slt-cli-${SLT_VERSION}-linux-x64.zip"

# Pin to what both .slcp files declare: `sdk: {id: gecko_sdk, version: 4.4.6}`.
GECKO_SDK_TAG="${GECKO_SDK_TAG:-v4.4.6}"
GECKO_SDK_URL="https://github.com/SiliconLabs/gecko_sdk.git"
SDK_DIR="$CACHE_DIR/gecko_sdk"

if [[ "${1:-}" == "clean" ]]; then
    echo ">> removing $CACHE_DIR"
    rm -rf "$CACHE_DIR"
    exit 0
fi

mkdir -p "$BIN_DIR"

# ---- slt ---------------------------------------------------------------
if ! command -v slt >/dev/null 2>&1 && [[ ! -x "$BIN_DIR/slt" ]]; then
    echo ">> downloading slt ${SLT_VERSION}"
    curl -fsSL -o "$CACHE_DIR/slt.zip" "$SLT_URL"
    unzip -oq "$CACHE_DIR/slt.zip" -d "$CACHE_DIR"
    chmod +x "$CACHE_DIR/slt"
    mv "$CACHE_DIR/slt" "$BIN_DIR/slt"
    rm -f "$CACHE_DIR/slt.zip"
else
    echo ">> slt already present, skipping download"
fi
export PATH="$BIN_DIR:$PATH"

# ---- slc-cli + ARM toolchain, via slt -----------------------------------
# slt manages its own package cache (typically under the user's home dir);
# we never guess its layout — always resolve real paths with `slt where`.
echo ">> installing slc-cli + gcc-arm-none-eabi + zap via slt (skips what's cached)"
slt install slc-cli gcc-arm-none-eabi zap --non-interactive

SLC_CLI_DIR="$(slt where slc-cli)"
TOOLCHAIN_DIR="$(slt where gcc-arm-none-eabi)"
# zap (ZCL Advanced Platform) generates zap-config.h etc. from config/zcl/*.zap
# — it's a separate tool slc-cli only invokes if it's told where to find it
# (slc generate --tool-path); it isn't bundled with slc-cli itself.
ZAP_DIR="$(slt where zap)"

if [[ -z "$SLC_CLI_DIR" || -z "$TOOLCHAIN_DIR" || -z "$ZAP_DIR" ]]; then
    echo "!! 'slt where' returned an empty path — slt install likely failed silently." >&2
    exit 1
fi

# ---- Gecko SDK 4.4.6, pinned by tag -------------------------------------
if [[ -d "$SDK_DIR/.git" ]]; then
    CURRENT_TAG="$(git -C "$SDK_DIR" describe --tags 2>/dev/null || echo "")"
    if [[ "$CURRENT_TAG" == "$GECKO_SDK_TAG" ]]; then
        echo ">> gecko_sdk $GECKO_SDK_TAG already present, skipping clone"
    else
        echo "!! $SDK_DIR exists but is at '$CURRENT_TAG', not $GECKO_SDK_TAG — re-cloning"
        rm -rf "$SDK_DIR"
    fi
fi
if [[ ! -d "$SDK_DIR/.git" ]]; then
    echo ">> cloning gecko_sdk $GECKO_SDK_TAG (this is a large repo; --depth 1 keeps it to one revision)"
    git clone --branch "$GECKO_SDK_TAG" --depth 1 "$GECKO_SDK_URL" "$SDK_DIR"
fi

# slc-cli refuses to generate from an SDK it didn't install itself via a
# signed package (exit 11, "Untrusted SDK") — a plain git clone is exactly
# that case. Trusting it is a one-time, per-SDK-path operation; slc-cli
# remembers it (in its own state under $HOME), so this is a no-op on a
# cache hit, matching every other step in this script.
export PATH="$BIN_DIR:$SLC_CLI_DIR:$PATH"
slc signature trust --sdk "$(cd "$SDK_DIR" && pwd)"

# ---- write env file for other scripts / CI steps to source --------------
cat > "$ENV_FILE" <<EOF
# Generated by tools/slc-install.sh — do not edit by hand.
export SLC_CLI_DIR="$(cd "$SLC_CLI_DIR" && pwd)"
export TOOLCHAIN_DIR="$(cd "$TOOLCHAIN_DIR" && pwd)"
export SDK_DIR="$(cd "$SDK_DIR" && pwd)"
export ZAP_DIR="$(cd "$ZAP_DIR" && pwd)"
# The slc launcher resolves its bundled Java via dirname "\$0" — put the
# directory on PATH, never symlink the slc binary itself elsewhere.
export PATH="\$SLC_CLI_DIR:\$TOOLCHAIN_DIR/bin:$(cd "$BIN_DIR" && pwd):\$PATH"
EOF

echo ">> wrote $ENV_FILE"
echo ">> SLC_CLI_DIR=$SLC_CLI_DIR"
echo ">> TOOLCHAIN_DIR=$TOOLCHAIN_DIR"
echo ">> SDK_DIR=$SDK_DIR"
echo ">> ZAP_DIR=$ZAP_DIR"
echo ">> done. Run: source $ENV_FILE"
